#!/bin/bash

if [ $# -lt 1 ]; then
	echo "USAGE $0 working_directory"
	exit 1
fi

DIR=$1

# changing temporarily to the working directory
curr_DIR=$PWD
cd $DIR

> input_list.csv
ls csv/*.csv | while read file; do
	basename="${file##*/}"
	name="${basename%.*}"
	echo -e "$file\toutput/report/$name.report\toutput/summary/$name.summary" >> input_list.csv
done

# 1. Run TST
APP_DIR=/home/yoel/services/vditech/tst/app
$APP_DIR/bin/tst input_list.csv

# 2. Plots
ls csv/*.csv > plots_list
python $APP_DIR/py/plot-all.py plots_list plots
python $APP_DIR/py/plot-failure.py Master-Failure-Report.csv plots/unstable

# back to the current directory
cd $curr_DIR
